name: release

on:
  push:
    tags:
      - "*"

jobs:
  build:
    uses: ./.github/workflows/build.yml

  create-release:
    name: Create Release
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v8
        with:
          path: artifacts
          skip-decompress: true

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: artifacts/*
          generate_release_notes: true
